# Generated by Django 5.0.6 on 2024-06-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='date',
        ),
    ]
