# Generated by Django 5.0.6 on 2024-06-03 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_weather_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
