# Generated by Django 5.0.6 on 2024-06-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_weather_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='updated_at',
        ),
    ]
